create table WIZ_DOCUMENT
(
   DOCUMENT_GUID                  char(36)                       not null,
   DOCUMENT_TITLE                 varchar(768)                   not null,
   DOCUMENT_LOCATION              varchar(768),
   DOCUMENT_NAME                  varchar(300),
   DOCUMENT_SEO                   varchar(300),
   DOCUMENT_URL                   varchar(2048),
   DOCUMENT_AUTHOR                varchar(150),
   DOCUMENT_KEYWORDS              varchar(300),
   DOCUMENT_TYPE                  varchar(20),
   DOCUMENT_OWNER                 varchar(150),
   DOCUMENT_FILE_TYPE             varchar(20),
   STYLE_GUID                     char(38),
   DT_CREATED                     char(19),
   DT_MODIFIED                    char(19),
   DT_ACCESSED                    char(19),
   DOCUMENT_ICON_INDEX            int,
   DOCUMENT_SYNC                  int,
   DOCUMENT_PROTECT               int,
   DOCUMENT_READ_COUNT            int,
   DOCUMENT_ATTACHEMENT_COUNT     int,
   DOCUMENT_INDEXED               int,
   DT_INFO_MODIFIED               char(19),
   DOCUMENT_INFO_MD5              char(32),
   DT_DATA_MODIFIED               char(19),
   DOCUMENT_DATA_MD5              char(32),
   DT_PARAM_MODIFIED              char(19),
   DOCUMENT_PARAM_MD5             char(32),
   WIZ_VERSION                    int64,
   INFO_CHANGED                   int,
   DATA_CHANGED                   int,
   primary key (DOCUMENT_GUID)
)
